---
- hosts: localhost
  connection: local
  become: true
  gather_facts: false

  vars:
    # set appropriate Debian branch (Unstable, Testing, 9.0, 10, 11)
    repository: Testing

  tasks:
    - name: install-crystal | Import key
      apt_key:
        url: https://download.opensuse.org/repositories/devel:languages:crystal/Debian_{{ repository }}/Release.key

    - name: install-crystal | Add repository
      apt_repository:
        repo: deb http://download.opensuse.org/repositories/devel:/languages:/crystal/Debian_{{ repository }}/ /
        filename: crystal

    - name: install-crystal | Install crystal package
      apt:
        name: crystal
        state: latest
        update_cache: true

    - name: install-crystal | Install recommended packages
      apt:
        name:
          - libssl-dev
          - libxml2-dev
          - libyaml-dev
          - libgmp-dev
          - libz-dev
        state: latest
        update_cache: true

# vim: ts=2 sts=0 sw=2 et
